#!/bin/bash
# change this file to your needs


echo "Adding some modules"

module add cmake

echo "#################"
echo "    COMPILING    "
echo "#################"


mkdir Build
cd Build
cmake ..
make

echo "#################"
echo "     RUNNING     "
echo "#################"

./pv021_project
cd ..
